# Generated by Django 3.1.5 on 2021-10-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(blank=True, max_length=120, null=True)),
                ('longitude', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location',
                'managed': True,
            },
        ),
    ]
